# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_recipe',
            name='recipe_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_creator', to='recipe.Recipe'),
        ),
    ]
