# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
