# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
