# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(default='EN_US', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Creator_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('creator_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ing_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('cook_time', models.PositiveIntegerField(default=0)),
                ('person_amount', models.PositiveIntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('parent_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_recipe', to='stomach_src.Recipe')),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_recipe', to='stomach_src.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('ing_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Ingredient')),
                ('storage_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Recipe')),
                ('tag_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gram', max_length=50)),
                ('short', models.CharField(default='g', max_length=10)),
                ('language', models.CharField(default='EN_US', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Recipe')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='storage_ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Unit'),
        ),
        migrations.AddField(
            model_name='ing_recipe',
            name='ing_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Ingredient'),
        ),
        migrations.AddField(
            model_name='ing_recipe',
            name='recipe_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Recipe'),
        ),
        migrations.AddField(
            model_name='ing_recipe',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Unit'),
        ),
        migrations.AddField(
            model_name='creator_recipe',
            name='recipe_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Recipe'),
        ),
        migrations.AddField(
            model_name='category_recipe',
            name='recipe_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Recipe'),
        ),
    ]
