# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stomach_src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_recipe',
            name='category_ID',
        ),
        migrations.RemoveField(
            model_name='category_recipe',
            name='recipe_ID',
        ),
        migrations.RemoveField(
            model_name='creator_recipe',
            name='creator_ID',
        ),
        migrations.RemoveField(
            model_name='creator_recipe',
            name='recipe_ID',
        ),
        migrations.RemoveField(
            model_name='ing_recipe',
            name='ing_ID',
        ),
        migrations.RemoveField(
            model_name='ing_recipe',
            name='recipe_ID',
        ),
        migrations.RemoveField(
            model_name='ing_recipe',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipe_versions',
            name='parent_ID',
        ),
        migrations.RemoveField(
            model_name='recipe_versions',
            name='recipe_ID',
        ),
        migrations.RemoveField(
            model_name='tag_recipe',
            name='recipe_ID',
        ),
        migrations.RemoveField(
            model_name='tag_recipe',
            name='tag_ID',
        ),
        migrations.RemoveField(
            model_name='user_recipe',
            name='recipe_ID',
        ),
        migrations.RemoveField(
            model_name='user_recipe',
            name='user_ID',
        ),
        migrations.AlterField(
            model_name='storage_ingredient',
            name='ing_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient'),
        ),
        migrations.AlterField(
            model_name='storage_ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Unit'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category_Recipe',
        ),
        migrations.DeleteModel(
            name='Creator_Recipe',
        ),
        migrations.DeleteModel(
            name='Ing_Recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Recipe_Versions',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tag_Recipe',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='User_Recipe',
        ),
    ]
