# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stomach_src', '0002_auto_20170517_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='ing_recipe',
            old_name='value',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='tag_recipe',
            name='recipe_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Recipe'),
        ),
        migrations.AddField(
            model_name='tag_recipe',
            name='tag_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Tag'),
        ),
        migrations.AddField(
            model_name='category_recipe',
            name='category_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Category'),
        ),
        migrations.AddField(
            model_name='category_recipe',
            name='recipe_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomach_src.Recipe'),
        ),
    ]
