# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stomach_src', '0002_auto_20170529_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='user_ID',
        ),
        migrations.RemoveField(
            model_name='storage_ingredient',
            name='ing_ID',
        ),
        migrations.RemoveField(
            model_name='storage_ingredient',
            name='storage_ID',
        ),
        migrations.RemoveField(
            model_name='storage_ingredient',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='Storage_Ingredient',
        ),
    ]
