# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomach_src', '0003_auto_20170523_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
